# Generated by Django 4.1.7 on 2023-03-17 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ethinicity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Occupation name", max_length=150, verbose_name="Name"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id_code", models.CharField(max_length=150, verbose_name="ID code")),
                (
                    "name_om",
                    models.CharField(
                        help_text="Person name in Afan Oromo",
                        max_length=150,
                        verbose_name="Afan Oromo Name",
                    ),
                ),
                (
                    "father_name_om",
                    models.CharField(
                        help_text="Person father name in Afan Oromo",
                        max_length=150,
                        verbose_name="Afan Oromo Father Name",
                    ),
                ),
                (
                    "gfather_name_om",
                    models.CharField(
                        help_text="Person grandfather name in Afan Oromo",
                        max_length=150,
                        verbose_name="Afan Oromo Grandfather Name",
                    ),
                ),
                (
                    "name_am",
                    models.CharField(
                        help_text="Person name in Amharic",
                        max_length=150,
                        verbose_name="Amharic Name",
                    ),
                ),
                (
                    "father_name_am",
                    models.CharField(
                        help_text="Person father name in Amharic",
                        max_length=150,
                        verbose_name="Amharic Father Name",
                    ),
                ),
                (
                    "gfather_name_am",
                    models.CharField(
                        help_text="Person grandfather name in Amharic",
                        max_length=150,
                        verbose_name="Amharic Grandfather Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Person first name in English",
                        max_length=150,
                        verbose_name="English First Name",
                    ),
                ),
                (
                    "father_name_en",
                    models.CharField(
                        help_text="Person father name in English",
                        max_length=150,
                        verbose_name="English Father Name",
                    ),
                ),
                (
                    "gfather_name_en",
                    models.CharField(
                        help_text="Person grandfather name in English",
                        max_length=150,
                        verbose_name="English Grandfather Name",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unknow")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                ("birthdate", models.DateField(verbose_name="Date of Birth")),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("AP", "A+"),
                            ("B", "B"),
                            ("BP", "B+"),
                            ("O", "O"),
                            ("OP", "O+"),
                            ("AB", "AB"),
                            ("ABP", "AB+"),
                            ("NRH", "No RH"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=3,
                        null=True,
                        verbose_name="Blood Group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start", models.DateField(verbose_name="Starting from")),
                ("end", models.DateField(blank=True, null=True, verbose_name="Until")),
                (
                    "is_current",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Current house?"
                    ),
                ),
                (
                    "is_rent",
                    models.BooleanField(default=False, verbose_name="Is rented?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        related_query_name="created_by_%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
