# Generated by Django 4.1.7 on 2023-03-17 16:23

import cities.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="ascii name"
                    ),
                ),
                (
                    "name_std",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="standard name"
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("population", models.IntegerField()),
                ("elevation", models.IntegerField(null=True)),
                ("kind", models.CharField(max_length=10)),
                ("timezone", models.CharField(max_length=40)),
            ],
            options={
                "verbose_name_plural": "cities",
                "abstract": False,
                "swappable": "CITIES_CITY_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="ascii name"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=2, unique=True)),
            ],
            options={
                "abstract": False,
                "swappable": "CITIES_CONTINENT_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="ascii name"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=2, unique=True)),
                ("code3", models.CharField(db_index=True, max_length=3, unique=True)),
                ("population", models.IntegerField()),
                ("area", models.IntegerField(null=True)),
                ("currency", models.CharField(max_length=3, null=True)),
                (
                    "currency_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "currency_symbol",
                    models.CharField(blank=True, max_length=31, null=True),
                ),
                ("language_codes", models.CharField(max_length=250, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("tld", models.CharField(max_length=5, verbose_name="TLD")),
                ("postal_code_format", models.CharField(max_length=127)),
                ("postal_code_regex", models.CharField(max_length=255)),
                ("capital", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "CITIES_COUNTRY_MODEL",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="ascii name"
                    ),
                ),
                (
                    "name_std",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="standard name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("population", models.IntegerField()),
            ],
            options={
                "abstract": False,
                "swappable": "CITIES_DISTRICT_MODEL",
            },
        ),
        migrations.CreateModel(
            name="AlternativeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("name", "Name"),
                            ("abbr", "Abbreviation"),
                            ("link", "Link"),
                            ("iata", "IATA (Airport) Code"),
                            ("icao", "ICAO (Airport) Code"),
                            ("faac", "FAAC (Airport) Code"),
                        ],
                        default="name",
                        max_length=4,
                    ),
                ),
                ("language_code", models.CharField(max_length=100)),
                ("is_preferred", models.BooleanField(default=False)),
                ("is_short", models.BooleanField(default=False)),
                ("is_colloquial", models.BooleanField(default=False)),
                ("is_historic", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostalCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="ascii name"
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("region_name", models.CharField(db_index=True, max_length=100)),
                ("subregion_name", models.CharField(db_index=True, max_length=100)),
                ("district_name", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="ascii name"
                    ),
                ),
                (
                    "name_std",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="standard name"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=200)),
                ("alt_names", models.ManyToManyField(to="cities.alternativename")),
            ],
        ),
        migrations.CreateModel(
            name="Subregion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="ascii name"
                    ),
                ),
                (
                    "name_std",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="standard name"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=200)),
                ("alt_names", models.ManyToManyField(to="cities.alternativename")),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=cities.models.SET_NULL_OR_CASCADE,
                        related_name="subregions",
                        to="cities.region",
                    ),
                ),
            ],
        ),
    ]
